//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SkinMan.rc
//
#define IDC_MYICON                      2
#define IDB_MITER                       102
#define IDB_BEVEL                       103
#define IDD_ABOUTBOX                    104
#define IDB_BITMAP2                     105
#define IDB_ROUND                       106
#define ID_HELP_ABOUT                   107
#define IDB_FLATCAP                     108
#define ID_FILE_EXIT                    109
#define IDB_ROUNDCAP                    110
#define IDI_SKINMAN                     111
#define IDB_SQUARECAP                   112
#define IDB_TRIANGLECAP                 114
#define IDC_SKINMAN                     115
#define IDB_TOOLRECT                    116
#define IDI_EDIT                        117
#define IDB_TOOLELLIPSE                 118
#define IDB_TOOLPOLYGON                 119
#define IDC_CURSORRECT                  120
#define IDB_TOOLTEXT                    121
#define IDB_TOOLCURVE                   122
#define IDB_TOOLSHAPE                   123
#define IDC_CURSORELLIPSE               124
#define IDB_TOOLLINES                   125
#define IDB_TOOLARROW                   126
#define IDC_CURSORTEXT                  127
#define IDB_TOOLHAND                    128
#define IDD_PROPTEXT                    129
#define IDB_TOOLGRADATION               130
#define IDI_UPDOWN                      131
#define IDI_GRADATION                   140
#define IDC_CURSORSHAPEEDIT             141
#define IDI_COPY                        141
#define IDD_PROPRECT                    142
#define IDB_COPY                        142
#define IDC_CURSORGRADATION             143
#define IDD_PROPNONE                    144
#define IDB_TOOLTRIMMING                145
#define IDC_CURSORARROW                 146
#define IDB_TOOLINSERTIMAGE             147
#define IDB_TOOLINSERTNEWKNOB           148
#define IDD_TOOL                        149
#define IDB_MIRRORH                     160
#define IDC_CURSORSHAPECLOSE            161
#define IDB_MIRRORV                     162
#define IDD_PROPSHAPE                   163
#define IDB_SHAPEEDIT                   164
#define IDC_CURSORHAND                  165
#define IDB_EAZEL                       166
#define IDD_DIALOG1                     167
#define IDD_SPLASH                      168
#define IDD_CANVASSIZE                  169
#define IDB_ZOOM1                       180
#define IDB_ZOOMIN                      181
#define IDD_GRIDSETUP                   182
#define IDB_ZOOMOUT                     183
#define IDB_FILENEW                     184
#define IDB_FILEOPEN                    185
#define IDB_EXPORTIMAGE                 186
#define IDB_BITMAP1                     187
#define IDB_FILESAVE                    188
#define IDI_NOFILE                      189
#define IDD_PROPIMAGE                   200
#define IDD_CMDBAR                      201
#define IDD_PROPELLIPSE                 202
#define IDI_ZOOMIN                      203
#define IDI_ZOOM1                       204
#define IDI_ZOOMOUT                     205
#define IDI_GRIDVISIBLE                 206
#define IDI_GRIDENABLE                  207
#define IDI_VISIBLE0                    208
#define IDI_VISIBLE1                    209
#define IDI_UP                          220
#define IDI_DOWN                        221
#define IDI_PARENT                      222
#define IDI_LOCK0                       223
#define IDI_LOCK1                       224
#define IDD_SETUP                       225
#define IDI_TRIMMING                    226
#define IDD_PROPLINES                   227
#define IDD_COLOR                       390
#define IDD_PNGOPTION                   393
#define IDC_CURSORGRADATE               394
#define IDD_RENAME                      395
#define IDC_CURSORMOVE                  396
#define IDD_PROPPOLYGON                 397
#define IDC_CURSORNESW                  398
#define IDD_TRANSFORM                   399
#define IDC_CURSORNWSE                  410
#define IDI_PIPETTE                     412
#define IDC_CURSORPOLYGON               413
#define IDC_CURSORPIPETTE               414
#define IDD_TREE                        416
#define IDD_PROPANIM                    418
#define IDD_PROPS1_EX1                  419
#define IDD_PROPS1                      419
#define IDB_UNDO                        420
#define IDB_REDO                        421
#define IDD_PROPS2                      425
#define IDC_CURSORTRIMMING              430
#define IDC_CURSORLINES                 431
#define IDC_CURSORARROW1                432
#define IDC_CURSORARROWPLUS             532
#define IDC_CURSORSHAPEPLUS             533
#define IDC_CURSORCURVEPLUS             534
#define IDC_CURSORCURVEEDIT             535
#define IDC_CURSORCURVECLOSE            536
#define IDC_DEFAULTGRIDX                550
#define IDC_DEFAULTGRIDY                551
#define IDC_UNDODEPTH                   552
#define IDC_UNDOLEVEL                   553
#define IDC_LANGID                      560
#define IDB_ALIGN_HORZ_LEFT             600
#define IDB_ALIGN_HORZ_CENTER           601
#define IDB_ALIGN_HORZ_RIGHT            602
#define IDB_ALIGN_VERT_TOP              603
#define IDB_ALIGN_VERT_CENTER           604
#define IDB_ALIGN_VERT_BOTTOM           605
#define IDB_DIST_HORZ_LEFT              606
#define IDB_DIST_HORZ_CENTER            607
#define IDB_DIST_HORZ_RIGHT             608
#define IDB_DIST_VERT_TOP               609
#define IDB_DIST_VERT_CENTER            610
#define IDB_DIST_VERT_BOTTOM            611
#define IDC_COLOR1                      1000
#define IDC_CHECK1                      1001
#define IDC_DISPGUIDE                   1002
#define IDC_TEXTUREXYSEPA               1003
#define IDC_PIE                         1004
#define IDC_CURSORMODE                  1005
#define IDC_ALLTEXT                     1006
#define IDC_ALWAYSFRONT                 1022
#define IDC_TOPMOST                     1023
#define IDC_COLOR2                      1024
#define IDC_COLOR3                      1025
#define IDC_SAVEPAL                     1035
#define IDC_LOADPAL                     1036
#define IDC_EMBOSSWIDTH                 1037
#define IDC_EMBOSSWIDTHSPIN             1038
#define IDC_EMBOSSDEPTH                 1039
#define IDC_EMBOSSDEPTHSPIN             1050
#define IDC_EMBOSSDEPTH2                1051
#define IDC_TYPE                        1052
#define IDC_EMBOSSDEPTH2SPIN            1053
#define IDC_VER                         1054
#define IDC_EMBOSSDEPTHSPIN2            1055
#define IDC_ANGLE                       1056
#define IDC_ANGLESPIN                   1057
#define IDC_TEXTURETYPE                 1058
#define IDC_TEXTURE                     1059
#define IDC_TEXTURESPIN                 1060
#define IDC_DIFFUSE                     1061
#define IDC_SLANT                       1062
#define IDC_SLANTSPIN                   1063
#define IDC_TEXTUREALPHA                1064
#define IDC_TEXTUREALPHASPIN            1065
#define IDC_TEXTURE2                    1066
#define IDC_TEXTURESPIN2                1067
#define IDC_TEXTUREZOOM                 1070
#define IDC_TEXTUREZOOMSPIN             1071
#define IDC_FRAME                       1072
#define IDC_TEXTUREROT                  1073
#define IDC_FONT                        1074
#define IDC_TEXTUREROTSPIN              1075
#define IDC_BOLD                        1076
#define IDC_TEXTUREZOOMYSPIN            1077
#define IDC_TEXTUREOFFYSPIN             1078
#define IDC_TEXTUREZOOMYSPIN2           1079
#define IDC_ITALIC                      1080
#define IDC_HEIGHT                      1081
#define IDC_TEXTUREOFFYSPIN2            1082
#define IDC_FRAMESX                     1083
#define IDC_TEXTUREROTSPIN2             1084
#define IDC_ALPHA                       1085
#define IDC_FRAMESY                     1086
#define IDC_ALPHA1                      1087
#define IDC_ALPHASPIN                   1089
#define IDC_ALPHA1SPIN                  1091
#define IDC_ALPHA2                      1092
#define IDC_ALPHA2SPIN                  1093
#define IDC_ALPHA3                      1094
#define IDC_ALPHA3SPIN                  1095
#define IDC_VISIBLE                     1096
#define IDC_ENABLE                      1097
#define IDC_X                           1100
#define IDC_XSPIN                       1101
#define IDC_Y                           1102
#define IDC_YSPIN                       1103
#define IDC_W                           1104
#define IDC_WSPIN                       1105
#define IDC_H                           1106
#define IDC_HSPIN                       1107
#define IDC_PARENT                      1110
#define IDC_DOCDIRSET                   1120
#define IDC_LINEAR                      1130
#define IDC_LINEARSPIN                  1131
#define IDC_SMOOTHER                    1132
#define IDC_SMOOTHERSPIN                1133
#define IDC_IMAGEDIRSET                 1153
#define IDC_UP                          1155
#define IDC_DOWN                        1156
#define IDC_UNDO                        1158
#define IDC_REDO                        1159
#define IDC_WIDTHSPIN                   1160
#define IDC_GRADATIONTYPE               1163
#define IDC_IMAGE                       1164
#define IDC_VERSION                     1165
#define IDC_KNOB                        1166
#define IDC_EMBOSSDIRSPIN               1168
#define IDC_OPERATION                   1169
#define IDC_GRIDVISIBLE                 1170
#define IDC_HANDMOVE                    1171
#define IDC_GRIDENABLE                  1172
#define IDC_TRANSPARENT                 1173
#define IDC_GRIDDISP                    1174
#define IDC_LINESTYPE2                  1175
#define IDC_DISPTREE                    1176
#define IDC_DOCDIR                      1177
#define IDC_FILL                        1178
#define IDC_DISPPROP                    1179
#define IDC_IMAGEDIR                    1180
#define IDC_WIDTH                       1181
#define IDC_DISPCOLOR                   1182
#define IDC_SELECT                      1183
#define IDC_RECT                        1184
#define IDC_ELLIPSE                     1185
#define IDC_EMBOSSDIR                   1186
#define IDC_TEXT                        1187
#define IDC_SHAPE                       1188
#define IDC_CLOSE                       1189
#define IDC_COLORMAP                    1200
#define IDC_CURVE                       1250
#define IDC_GRADATE                     1251
#define IDC_GRADATION                   1252
#define IDC_DIFFUSESPIN                 1253
#define IDC_POLYGON                     1254
#define IDC_CORNERC1                    1255
#define IDC_CORNERC2                    1292
#define IDC_CORNERC3                    1293
#define IDC_CORNERC4                    1294
#define IDC_EMBOSSDIRENABLE             1296
#define IDC_BORDER                      1298
#define IDC_BORDERI                     1299
#define IDC_BORDERASFILL                1302
#define IDC_BORDER2                     1303
#define IDC_RESET                       1304
#define IDC_NAME                        1305
#define IDC_BORDERJOIN                  1306
#define IDC_ZOOMX                       1307
#define IDC_VERTEX                      1308
#define IDC_ZOOMY                       1309
#define IDC_VERTEXSPIN                  1310
#define IDC_STARDEPTH                   1311
#define IDC_STARDEPTHSPIN               1312
#define IDC_COLORBAR                    1321
#define IDC_SPECULARTYPE                1330
#define IDC_SPECULARTYPE2               1331
#define IDC_SPECULARDIR                 1332
#define IDC_SPECULARDIRSPIN             1333
#define IDC_SPECULARDIR2                1334
#define IDC_SPECULARDIR2SPIN            1335
#define IDC_SPECULAROFF                 1336
#define IDC_SPECULAROFFSPIN             1337
#define IDC_SPECULAROFF2                1338
#define IDC_SPECULAROFF2SPIN            1339
#define IDC_SPECULAR                    1340
#define IDC_SPECULARSPIN                1341
#define IDC_SPECULAR2                   1342
#define IDC_SPECULAR2SPIN               1343
#define IDC_HIGHLIGHT                   1410
#define IDC_HIGHLIGHTSPIN               1411
#define IDC_HIGHLIGHT2                  1412
#define IDC_HIGHLIGHT2SPIN              1413
#define IDC_HIGHLIGHTWIDTH              1414
#define IDC_HIGHLIGHTWIDTHSPIN          1415
#define IDC_HIGHLIGHTWIDTH2             1416
#define IDC_HIGHLIGHTWIDTH2SPIN         1417
#define IDC_AMBIENT                     1418
#define IDC_AMBIENTSPIN                 1419
#define IDC_AMBIENT2                    1420
#define IDC_AMBIENT2SPIN                1421
#define IDC_LINETYPE                    1450
#define IDC_ZOOMIN                      1460
#define IDC_ZOOMOUT                     1461
#define IDC_ZOOM1                       1462
#define IDC_SHADOWCOLOR                 1500
#define IDC_SHADOWDIRENABLE             1501
#define IDC_SHADOWDIR                   1502
#define IDC_SHADOWDIRSPIN               1503
#define IDC_SHADOWOFFSET                1504
#define IDC_SHADOWOFFSETSPIN            1505
#define IDC_SHADOWDENSITY               1506
#define IDC_SHADOWDENSITYSPIN           1507
#define IDC_SHADOWDIFFUSE               1508
#define IDC_SHADOWDIFFUSESPIN           1509
#define IDC_ISHADOWCOLOR                1510
#define IDC_SHADOWCOLOR2                1511
#define IDC_ISHADOWDIRENABLE            1512
#define IDC_ISHADOWDIR                  1513
#define IDC_ISHADOWDIRSPIN              1514
#define IDC_ISHADOWOFFSET               1515
#define IDC_ISHADOWOFFSETSPIN           1516
#define IDC_ISHADOWDENSITY              1517
#define IDC_ISHADOWDENSITYSPIN          1518
#define IDC_ISHADOWDIFFUSE              1519
#define IDC_ISHADOWDIFFUSESPIN          1520
#define IDC_ANTIALIAS                   1521
#define IDC_TENSION                     1530
#define IDC_TENSIONSPIN                 1531
#define IDC_TWIST                       1532
#define IDC_TWISTSPIN                   1533
#define IDC_START                       1540
#define IDC_STARTSPIN                   1541
#define IDC_STOP                        1542
#define IDC_STOPSPIN                    1543
#define IDC_L                           1551
#define IDC_S                           1552
#define IDC_R                           1553
#define IDC_G                           1554
#define IDC_B                           1555
#define IDC_COLOR                       1556
#define IDC_COLFILL1                    1600
#define IDC_COLFILL2                    1601
#define IDC_COLBORDER                   1602
#define IDC_COLDSHADOW                  1603
#define IDC_COLISHADOW                  1604
#define IDC_PAL0                        1700
#define IDC_PAL1                        1701
#define IDC_PAL2                        1702
#define IDC_PAL3                        1703
#define IDC_PAL4                        1704
#define IDC_PAL5                        1705
#define IDC_PAL6                        1706
#define IDC_PAL7                        1707
#define IDC_PAL8                        1708
#define IDC_PAL9                        1709
#define IDC_PAL10                       1710
#define IDC_PAL11                       1711
#define IDC_PAL12                       1712
#define IDC_PAL13                       1713
#define IDC_PAL14                       1714
#define IDC_PAL15                       1715
#define IDC_PAL16                       1716
#define IDC_PAL17                       1717
#define IDC_PAL18                       1718
#define IDC_PAL19                       1719
#define IDC_PAL20                       1720
#define IDC_PAL21                       1721
#define IDC_PAL22                       1722
#define IDC_PAL23                       1723
#define IDC_PIPETTE                     1800
#define IDC_LINECAP                     1850
#define IDC_LINECAP2                    1851
#define IDC_TRIMMING                    1900
#define IDC_TRIMMING2                   1901
#define IDC_LINES                       1902
#define IDC_FIX                         1950
#define IDC_FONTSIZE                    2001
#define IDC_FONTSIZESPIN                2002
#define IDC_FONTASPECT                  2003
#define IDC_FONTASPECTSPIN              2004
#define IDC_AUTOSIZE                    2005
#define IDC_FONTSPACING                 2006
#define IDC_FONTSPACINGSPIN             2007
#define IDC_FONTSIZEUNIT                2008
#define IDC_AUTOSIZE2                   2009
#define IDC_SMALLFONTOPT                2020
#define IDC_PATHOFFSET                  2021
#define IDC_PATHOFFSETSPIN              2022
#define IDC_USETEXTPATH                 2023
#define IDC_KEEPDIR                     2024
#define IDC_LIBDIR                      2100
#define IDC_LIBDIRSET                   2101
#define IDC_PALDIR                      2102
#define IDC_PALDIRSET                   2103
#define IDC_ROUNDX1                     2201
#define IDC_ROUNDX1SPIN                 2202
#define IDC_ROUNDX2                     2203
#define IDC_ROUNDX2SPIN                 2204
#define IDC_ROUNDX3                     2205
#define IDC_ROUNDX3SPIN                 2206
#define IDC_ROUNDX4                     2207
#define IDC_ROUNDX4SPIN                 2208
#define IDC_ROUNDSEPARATE               2209
#define IDC_ROUNDY1                     2211
#define IDC_ROUNDY1SPIN                 2212
#define IDC_ROUNDY2                     2213
#define IDC_ROUNDY2SPIN                 2214
#define IDC_ROUNDY3                     2215
#define IDC_ROUNDY3SPIN                 2216
#define IDC_ROUNDY4                     2217
#define IDC_ROUNDY4SPIN                 2218
#define IDC_ROUNDXYSEPARATE             2219
#define IDC_MSG1                        2300
#define IDC_MSG2                        2301
#define IDC_TEXTPATH                    2310
#define IDC_CHECK2                      2311
#define IDC_PAGEPRIM                    2413
#define IDC_PAGEANIM                    2414
#define IDC_ANIMOFFXFROM                3000
#define IDC_ANIMOFFXFROMSPIN            3001
#define IDC_ANIMOFFX                    3002
#define IDC_ANIMOFFXTO                  3003
#define IDC_ANIMOFFXTOSPIN              3004
#define IDC_ANIMOFFYFROM                3005
#define IDC_ANIMOFFYFROMSPIN            3006
#define IDC_ANIMOFFY                    3007
#define IDC_ANIMOFFYTO                  3008
#define IDC_ANIMOFFYTOSPIN              3009
#define IDC_ANIMANGLEFROM               3010
#define IDC_ANIMANGLEFROMSPIN           3011
#define IDC_ANIMANGLE                   3012
#define IDC_ANIMANGLETO                 3013
#define IDC_ANIMANGLETOSPIN             3014
#define IDC_ANIMZOOMFROM                3015
#define IDC_ANIMZOOMFROMSPIN            3016
#define IDC_ANIMZOOM                    3017
#define IDC_ANIMZOOMTO                  3018
#define IDC_ANIMZOOMTOSPIN              3019
#define IDC_ANIMROTCENTERX              3020
#define IDC_ANIMROTCENTERXSPIN          3021
#define IDC_ANIMROTCENTERY              3022
#define IDC_ANIMROTCENTERYSPIN          3023
#define IDC_ANIMALPHAFROM               3024
#define IDC_ANIMALPHAFROMSPIN           3025
#define IDC_ANIMALPHA                   3026
#define IDC_ANIMALPHATO                 3027
#define IDC_ANIMALPHATOSPIN             3028
#define IDC_ANIMBRIGHTNESSFROM          3029
#define IDC_ANIMBRIGHTNESSFROMSPIN      3030
#define IDC_ANIMBRIGHTNESS              3031
#define IDC_ANIMBRIGHTNESSTO            3032
#define IDC_ANIMBRIGHTNESSTOSPIN        3033
#define IDC_ANIMCONTRASTFROM            3034
#define IDC_ANIMCONTRASTFROMSPIN        3035
#define IDC_ANIMCONTRAST                3036
#define IDC_ANIMCONTRASTTO              3037
#define IDC_ANIMCONTRASTTOSPIN          3038
#define IDC_ANIMSATURATIONFROM          3039
#define IDC_ANIMSATURATIONFROMSPIN      3040
#define IDC_ANIMSATURATION              3041
#define IDC_ANIMSATURATIONTO            3042
#define IDC_ANIMSATURATIONTOSPIN        3043
#define IDC_ANIMHUEFROM                 3044
#define IDC_ANIMHUEFROMSPIN             3045
#define IDC_ANIMHUE                     3046
#define IDC_ANIMHUETO                   3047
#define IDC_ANIMHUETOSPIN               3048
#define IDC_USEANIMMASK                 3099
#define IDC_ANIMMASKSTART               3100
#define IDC_ANIMMASKSTARTFROM           3101
#define IDC_ANIMMASKSTARTFROMSPIN       3102
#define IDC_ANIMMASKSTARTTO             3103
#define IDC_ANIMMASKSTARTTOSPIN         3104
#define IDC_ANIMMASKSTOP                3105
#define IDC_ANIMMASKSTOPFROM            3106
#define IDC_ANIMMASKSTOPFROMSPIN        3107
#define IDC_ANIMMASKSTOPTO              3108
#define IDC_ANIMMASKSTOPTOSPIN          3109
#define IDC_ANIMMASKTYPE                3110
#define IDC_ANIMMASKGRADATION           3111
#define IDC_ANIMMASKGRADATIONSPIN       3112
#define IDC_ANIMMASKGRADATIONTYPE       3113
#define IDC_USEFRAMEMASK                3114
#define IDC_FRAMEMASKSTART              3115
#define IDC_FRAMEMASKSTARTSPIN          3116
#define IDC_FRAMEMASKSTOP               3117
#define IDC_FRAMEMASKSTOPSPIN           3118
#define IDC_BORDERTYPE                  3200
#define IDC_COMBO1                      3203
#define IDC_TEXTUREZOOMX                3204
#define IDC_TEXTUREZOOMY                3205
#define IDC_TEXTUREZOOMXSPIN            3206
#define IDC_TEXTUREOFFX                 3207
#define IDC_TEXTUREOFFY                 3208
#define IDC_TEXTUREOFFXSPIN             3209
#define IDC_TEXTUREZOOMXYSEPA           3210
#define IDC_COPCOODINATE                3211
#define IDC_COPYCOODINATE               3212
#define IDC_PROP_POS                    10100
#define IDC_PROP_SIZE                   10101
#define IDC_PROP_OPERATION              10102
#define IDC_PROP_ANGLE                  10103
#define IDC_PROP_CORNER                 10104
#define IDC_PROP_ANGLE2                 10104
#define IDC_PROP_COLOR                  10105
#define IDC_PROP_SLANT                  10106
#define IDC_PROP_ALPHA                  10107
#define IDC_PROP_ALPHA1                 10108
#define IDC_PROP_ALPHA2                 10109
#define IDC_PROP_FILL1                  10110
#define IDC_PROP_FILL2                  10111
#define IDC_PROP_BORDER                 10112
#define IDC_PROP_GRADATION              10113
#define IDC_PROP_MASTERALPHA            10114
#define IDC_PROP_BORDERWIDTH            10115
#define IDC_PROP_BORDERJOIN             10116
#define IDC_PROP_DIFFUSE                10117
#define IDC_PROP_SMOOTHER               10118
#define IDC_PROP_SPEC                   10120
#define IDC_PROP_SPEC_LIGHT1            10121
#define IDC_PROP_SPEC_LIGHT2            10122
#define IDC_PROP_SPEC_OFF               10123
#define IDC_PROP_SPEC_TYPE              10125
#define IDC_PROP_SPEC_DIR               10126
#define IDC_PROP_SPEC_SPEC              10127
#define IDC_PROP_SPEC_HILIGHT           10128
#define IDC_PROP_SPEC_HILIGHTW          10129
#define IDC_PROP_SPEC_AMBIENT           10130
#define IDC_PROP_EMBOSS                 10131
#define IDC_PROP_EMBOSS_DIR             10132
#define IDC_PROP_EMBOSS_WIDTH           10133
#define IDC_PROP_EMBOSS_DEPTH           10134
#define IDC_PROP_EMBOSS_DEPTHB          10135
#define IDC_PROP_EMBOSS_DEPTHF          10136
#define IDC_PROP_TEX                    10140
#define IDC_PROP_TEX_TYPE               10141
#define IDC_PROP_TEX_INTENSITY          10142
#define IDC_PROP_TEX_X                  10143
#define IDC_PROP_TEX_Y                  10144
#define IDC_PROP_TEX_ZOOM               10145
#define IDC_PROP_TEX_OFF                10146
#define IDC_PROP_TEX_ROT                10147
#define IDC_PROP_TEX_INTENSITY2         10148
#define IDC_PROP_SHADOW                 10150
#define IDC_PROP_SHADOW_DROP            10151
#define IDC_PROP_SHADOW_INSIDE          10152
#define IDC_PROP_SHADOW_COLOR           10153
#define IDC_PROP_SHADOW_DIR             10154
#define IDC_PROP_SHADOW_OFFSET          10155
#define IDC_PROP_SHADOW_DENSITY         10156
#define IDC_PROP_SHADOW_DIFFUSE         10157
#define IDC_PROP_TEX_ZOOM8              10158
#define IDC_PROP_START                  10160
#define IDC_PROP_STOP                   10161
#define IDC_PROP_TEXT                   10170
#define IDC_PROP_FONT                   10171
#define IDC_PROP_FONTSIZE               10172
#define IDC_PROP_FONTASPECT             10173
#define IDC_PROP_FONTSPACING            10174
#define IDC_PROP_FONTSPACING3           10176
#define IDC_PROP_VERTEX                 10180
#define IDC_PROP_STARDEPTH              10181
#define IDC_PROP_CURVE                  10182
#define IDC_PROP_TWIST                  10183
#define IDC_PROP_LINECAP                10184
#define IDC_PROP_CLOSE                  10185
#define IDC_PROP_LINETYPE               10186
#define IDI_ITEMRECT                    32400
#define IDI_ITEMELLIPSE                 32401
#define IDI_ITEMPOLYGON                 32402
#define IDI_ITEMTEXT                    32403
#define IDI_ITEMSHAPE                   32404
#define IDI_ITEMLINES                   32405
#define IDI_ITEMIMAGE                   32406
#define IDI_ITEMGROUP                   32407
#define IDI_ITEMRECT_S                  32410
#define IDI_ITEMELLIPSE_S               32411
#define IDI_ITEMPOLYGON_S               32412
#define IDI_ITEMTEXT_S                  32413
#define IDI_ITEMSHAPE_S                 32414
#define IDI_ITEMLINES_S                 32415
#define IDI_ITEMIMAGE_S                 32416
#define IDI_ITEMGROUP_S                 32417
#define IDI_HANDMOVE                    32513
#define IDI_GRADATE                     32516
#define IDI_VISIBLESOLO0                32520
#define IDI_VISIBLESOLO1                32521
#define IDI_CMDGROUP                    32523
#define IDI_CMDUNGROUP                  32524
#define IDI_DISPTREE                    32525
#define IDI_DISPPROP                    32526
#define IDI_DISPCOLOR                   32527
#define IDI_IMAGE1                      32528
#define IDI_ITEMRECT_H                  32528
#define IDI_ITEMLINES_H                 32529
#define IDI_ITEMELLIPSE_H               32530
#define IDI_ITEMGROUP_H                 32531
#define IDI_ITEMIMAGE_H                 32532
#define IDI_ITEMPOLYGON_H               32533
#define IDI_ITEMSHAPE_H                 32534
#define IDI_ITEMTEXT_S1                 32535
#define IDI_ITEMTEXT_H                  32535
#define IDI_SKINMAN1                    32536
#define IDI_SMALL                       32536
#define ID_FILE_OPEN                    32800
#define ID_FILE_SAVEAS                  32801
#define ID_FILE_SAVE                    32802
#define ID_FILE_NEW                     32803
#define ID_FILE_EXPORTIMAGE             32804
#define ID_FILE_SETUP                   32806
#define ID_FILE_IMPORT                  32807
#define ID_FILE_EXPORT                  32808
#define ID_EDIT_UNDO                    32809
#define ID_EDIT_REDO                    32810
#define ID_EDIT_SELECTALL               32813
#define ID_EDIT_SELECTVISIBLE           32815
#define ID_PRIMITIVE_PASTECOLOR         32834
#define ID_PRIMITIVE_COPYPRIMITIVE      32835
#define ID_PRIMITIVE_PASTEPRIMITIVE     32836
#define ID_PRIMITIVE_DELETEPRIMITIVE    32837
#define ID_PRIMITIVE_MOVETOPARENT       32838
#define ID_PRIMITIVE_MOVETOFOREGROUND   32839
#define ID_PRIMITIVE_MOVETOBACKGROUND   32840
#define ID_PRIMITIVE_EDITSHAPE          32841
#define ID_PRIMITIVE_MIRRORHORIZONTAL   32842
#define ID_PRIMITIVE_MIRRORVERTICAL     32843
#define ID_PRIMITIVE_CUTPRIMITIVE       32845
#define ID_PRIMITIVE_PASTEEFFECTS       32846
#define ID_PRIMITIVE_TRANSFORM          32848
#define ID_PRIMITIVE_RENAME             32849
#define ID_PRIMITIVE_GROUP              32850
#define ID_PRIMITIVE_UNGROUP            32851
#define ID_PRIMITIVE_EDITKNOB           32852
#define ID_PRIMITIVE_MAKECIRCLE         32853
#define ID_PRIMITIVE_ALIGNHORZL         32860
#define ID_PRIMITIVE_ALIGNHORZC         32861
#define ID_PRIMITIVE_ALIGNHORZR         32862
#define ID_PRIMITIVE_ALIGNVERTT         32863
#define ID_PRIMITIVE_ALIGNVERTC         32864
#define ID_PRIMITIVE_ALIGNVERTB         32865
#define ID_PRIMITIVE_DISTRIBUTEHORZL    32866
#define ID_PRIMITIVE_DISTRIBUTEHORZC    32867
#define ID_PRIMITIVE_DISTRIBUTEHORZR    32868
#define ID_PRIMITIVE_DISTRIBUTEVERTT    32869
#define ID_PRIMITIVE_DISTRIBUTEVERTC    32870
#define ID_PRIMITIVE_DISTRIBUTEVERTB    32871
#define ID_PRIMITIVE_OPENORMAL          32900
#define ID_PRIMITIVE_OPEADD             32901
#define ID_PRIMITIVE_OPESUB             32902
#define ID_PRIMITIVE_OPEMUL             32903
#define ID_DISPLAY_ZOOMIN               33860
#define ID_DISPLAY_ZOOMOUT              33861
#define ID_DISPLAY_DRAFT                33862
#define ID_DISPLAY_RENDER               33864
#define ID_DISPLAY_GRID                 33865
#define ID_TOOL_RECT                    33866
#define ID_TOOL_ELLIPSE                 33867
#define ID_TOOL_TEXT                    33868
#define ID_TOOL_ARROW                   33869
#define ID_TOOL_CURVE                   33870
#define ID_TOOL_SHAPE                   33871
#define ID_TOOL_LINES                   33872
#define ID_TOOL_INSERTIMAGE             33873
#define ID_TOOL_HAND                    33874
#define ID_TOOL_GRADATION               33875
#define ID_TOOL_POLYGON                 33876
#define ID_TOOL_TRIMMING                33877
#define ID_CANVAS_SIZE                  33878
#define ID_CANVAS_GRID                  33879
#define ID_CANVAS_BACKGROUND            33880
#define ID_CANVAS_WORKSPACE             33881
#define ID_CANVAS_TRIMMING              33882
#define ID_CANVAS_TRIMMINGVISIBLE       33883
#define ID_DISPLAY_COLOR                33900
#define ID_DISPLAY_PROPERTIES           33901
#define ID_DISPLAY_TREE                 33902
#define ID_FILE_1                       34001
#define ID_FILE_2                       34002
#define ID_FILE_3                       34003
#define ID_FILE_4                       34004
#define ID_FILE_5                       34005
#define ID_FILE_6                       34006
#define ID_FILE_7                       34007
#define ID_FILE_8                       34008
#define IDS_APP_TITLE                   40000
#define ID_PRIMITIVE_REFRESH            40001
#define ID_TOOL_INSERTNEWKNOB           40002
#define ID_PRIMITIVE_MOVETOTOPMOST      40003
#define ID_PRIMITIVE_ALIGN              40006
#define ID_ALIGN_ALIGNHORZLEFT          40007
#define ID_ALIGN_ALIGNHORZCENTER        40008
#define ID_ALIGN_ALIGNHORZRIGHT         40009
#define ID_ALIGN_ALIGNVERTTOP           40010
#define ID_ALIGN_ALIGNVERTCENTER        40011
#define ID_ALIGN_ALIGNVERTBOTTOM        40012
#define ID_CANVAS_TRANSPARENTBG         40013
#define ID_DISPLAY_ZOOM1                40014
#define ID_PRIMITIVE_CUTPRIMITIVE40015  40015
#define ID_PRIMITIVE_EXTRACTFILE        40016
#define ID_PRIMITIVE_COPYCOODINATE      40017
#define ID_PRIMITIVE_COPYSIZE           40018
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         40019
#define _APS_NEXT_CONTROL_VALUE         3213
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
